[package]
name = "slurm-web"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["serde_json", "json"] }
rocket_dyn_templates = { version = "0.2.0", features = ["minijinja"] }
